### ISSUE TITLE
path argument in documentation

### ISSUE THREAD

**Issue by maggiesavovska** [ZeroDragon/niceLogger#1]
Hi, I like your logger. I know it's an older project. I wonder why more people are not using this.

Anyway, you might want to update the documentation. 

The ".config" method takes two arguments. The second one should be the path which most people will pass in as __dirname. That is how I got it working.
logger = require('nicelogger').config(config.logger, __dirname);

thanks!

**Comment by ZeroDragon** [comment]
### Changes
Info updated on commit [b0bb435](https://github.com/ZeroDragon/niceLogger/commit/b0bb435a905cfd844320c4c5816df861fa5a4248).
Also added your reference in the change log, thanks!

### Actions to do [optional]:
`npm update` to version **17.4.4-b**

### PS
Even if this repo is old, is not forgotten! (and it works on node 7.+)
